def printStartupMessage():
    print("=== Dynamic Cat Pic Discord Bot ===")
    print("Features:")
    print("- Automatically balances image percentages")
    print("- Supports user-added images in assets/ folder")
    print("- Special 'MAN' image with 0.1% chance")
    print("- Dynamic Cat API image management")
    print("\nSetup:")
    print("1. pip install discord.py aiohttp aiofiles requests")
    print("2. Place 'MAN' horse image as 'assets/man_horse.jpg'")
    print("3. Add your own cat images to 'assets/' folder")
    print("4. Add camera roll images to 'assets/camera_roll/' folder")
    print("5. Set bot token and run!")
    print("\nThe bot will automatically:")
    print("- Scan for existing images")
    print("- Calculate needed Cat API images")
    print("- Download/remove Cat API images to balance percentages")
    print("=" * 50)